In [2]:
# Importing modules

import cv2 as cv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Reading the image where the first arg is the path and the second is the color format of the image that is to be read.
pic = cv.imread(
    "C:/Users/namit/OneDrive/Desktop/Desktop/PROJECTS(CODE)/NNML/Project/pics/pic1.jpg",
    cv.IMREAD_COLOR,
)

# Showing the image in a seperate window where the first arg is the Title of the window and the second is the image.
cv.imshow("image", pic)


# Waiting for "0" key to be pressed to exit from the window


cv.waitKey(0)

# Exiting from the window
cv.destroyAllWindows()

# .shape function will return the height x width of the image with the number of channels used by the picture i.e. RGB.
# NOTE: IN greyscale image there is no RGB.

pic.shape

(1280, 720, 3)

In [4]:
# cv. imread will read the picture that is to be read and gives us the RGB values of each pixcel in the image.
print(pic.shape)
print(pic)

(1280, 720, 3)
[[[45 33 33]
  [47 35 35]
  [50 36 37]
  ...
  [45 32 48]
  [46 33 47]
  [44 31 45]]

 [[46 34 34]
  [49 37 37]
  [55 41 42]
  ...
  [47 34 48]
  [48 36 48]
  [47 35 47]]

 [[49 37 37]
  [51 39 39]
  [53 39 40]
  ...
  [46 32 43]
  [47 33 44]
  [47 33 44]]

 ...

 [[29 28 44]
  [29 28 44]
  [25 22 38]
  ...
  [22 33 83]
  [30 39 89]
  [29 38 88]]

 [[28 25 40]
  [26 23 38]
  [27 24 40]
  ...
  [18 30 78]
  [29 39 87]
  [27 37 85]]

 [[24 21 36]
  [24 21 36]
  [28 25 41]
  ...
  [19 32 78]
  [25 35 83]
  [24 34 82]]]


In [7]:
b, g, r = cv.split(pic)

cv.imshow("BLUEIMG", g)

cv.waitKey(0)

cv.destroyAllWindows()

# NOTE: The picture in CV will be read as BGR format and when we use .split the Blue, Green and Red values will be splitted into each images and gets stored. Each image will represent its color.

: 